version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'reservations'
       MYSQL_USER: 'root@123'
       MYSQL_PASSWORD: 'root@123'
       MYSQL_ROOT_PASSWORD: 'root@123'
  web:
    build:
      context: .
      dockerfile: .DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/LittleLemon
    ports:
      - "8000:8000"
    depends_on:
      - db